### ISSUE TITLE
Basic distributed Integration Test

### ISSUE THREAD

**Issue by pbrm4** [airavata-courses/epsilon#1]
For compatibility purposes can you each make a server status API? 
@Abhinav805 As discussed try in java or .net
@chanakyaken Can you do it in python

The API should be simple and respond in the following JSON format:
{
    "success": true,
    "message": "Server is functioning and active on: 19031"
}

The base API path for your microservice should be /_language_/api/
This API's end point should be /statuscheck

I will call these services from the api-gateway

**Comment by chanakyaken** [comment]
@pbrm4  Sure, will let you know once it is done!

**Comment by Abhinav805** [comment]
@pbrm4 @chanakyaken  sure I am trying in Java to get to learn also in Java. 

I installed the Java, Maven , IntelliJ and created one simple web api. Still some issues found. Now Trying other ways using Spring 


When the API will be ready will test with server API and test.

Will update you guys once done.

**Comment by Abhinav805** [comment]
@pbrm4 @chanakyaken 

So the code for the required api response is done and send to you. Please integrate with your code and let me know any issues or modification. Thanks

**Comment by chanakyaken** [comment]
@Abhinav805  I have also sent my code to @pbrm4 . We will meet tomorrow in Luddy 3069 at 12:00 pm to discuss further steps and plan our Project accordingly.

**Comment by Abhinav805** [comment]
Cool see you guys tomorrow.

**Comment by pbrm4** [comment]
I have integrated and tested the system with:
     NodeJS API gateway, NodeJS MS, Python MS, Java MS.

Tomorrow let us discuss functional requirements and break them into services and the general flow. 
Thanks. See you guys tomorrow. 
I am closing this issue.
