### ISSUE TITLE
Meeting, 20th Jan 2022 - Luddy

### ISSUE THREAD

**Issue by Abhinav805** [airavata-courses/epsilon#2]

**Comment by Abhinav805** [comment]
Like discussed in our meeting 

My task is to connect Java with MongoDB first.

Will download MongoDB and will setting up required connections and test the connection.

**Comment by Abhinav805** [comment]
Currently API for Java with Mongo is done. Will do changes if required. Next task are

1) Napkin Diagram. Will check for Online Gifi
2) Documenting Architecture diagram
3) Modifying API for better performance
4) Connecting with team for integrating code properly

**Comment by Abhinav805** [comment]
Now closing the issues after completing the tasks.

**Comment by pbrm4** [comment]
https://docs.google.com/spreadsheets/d/17UQIcS07eRWhDc1k5NcxW1LQRDfUUyjSG3FgSL0R9bI/edit?usp=sharing
Refer this for task distribution
