### ISSUE TITLE
Project 1 review

### ISSUE THREAD

**Issue by prernaa96** [airavata-courses/epsilon#33]
Hello Team Epsilon,

I ran your project and I found it to be a smooth experience. I'll summarize my experience -

- I liked the log in through Google feature.
- The storing of user searches is amazing
- Also, I liked the map plots and automatic selection of state on the next page. This is what we found difficult to do.
- The instructions were easy to understand and the project was quick to run using docker.

Improvements:

- I came across this issue when I viewed a plot for a time period and then returned to the map page. When I returned to the map page, I wasn't able to see my search until I refreshed the page. I think this can be improved.
- I found a weird issue. I am attaching the screenshot for your reference. I selected the "KBOX" station (somewhere around New York) , went to the next page and then returned to the map page. I got an undefined entry probably because I didn't run hit for getting the plot.

<img width="1440" alt="map" src="https://user-images.githubusercontent.com/73582366/153333117-cf24beb4-1511-4c30-b398-9f8c342eafe5.png">

Overall it was a great experience and you guys have done an amazing job.

Best,
Team DSDummies.

**Comment by chanakyaken** [comment]
> * I came across this issue when I viewed a plot for a time period and then returned to the map page. When I returned to the map page, I wasn't able to see my search until I refreshed the page. I think this can be improved.

Hi Prernaa,

The issue which you pointed is a known issue to us, we did find that just before the submission was due and hence were not able to do much about it but thanks for letting us know, we would try fixing it in the next release.
I'll create a new issue for it now.

Thanks and Regards
Chanakya

Team Epsilon

**Comment by pbrm4** [comment]
> * I found a weird issue. I am attaching the screenshot for your reference. I selected the "KBOX" station (somewhere around New York) , went to the next page and then returned to the map page. I got an undefined entry probably because I didn't run hit for getting the plot.

Hi,
Thank you for the feedback. 
Thanks for reporting this issue. Our docker hub repo wasn't updated and we were testing locally. I will look into this.

Thanks,
Pramod
Team Epsilon.
