### ISSUE TITLE
Project1 review by Codist

### ISSUE THREAD

**Issue by tanukansalgit** [airavata-courses/epsilon#35]
1. UI looks fantastic.
2.  I didnt understand why logging service was made talking to the Radar Service( Node.js ), i think it could be a general service if made communication with api gateway.
3. Session-maintainance process is really impressive.
4. I am particularly impressed by the choice of databases for the specific purposes.

**Comment by pbrm4** [comment]
Thanks for the feedback. 
Regarding point 2 we are planning on using the logging service as a common tool for application log processing as well. Currently, this felt like an easy way to achieve this. But yeah, it is a bad choice. 

Thank you,
Pramod, Team Epsilon
