### ISSUE TITLE
Project Review (Dexlab)

### ISSUE THREAD

**Issue by saurabh737** [airavata-courses/epsilon#36]
Hello Team Epsilon,

The instructions were simple to follow, and the project ran quickly thanks to the use of docker.
I like to appreciate the map plots and automated state selection.
The ability to save user searches is incredible.

One suggestion after the plot is rendered is you can remove the loading message from the background.
<img width="1440" alt="Screenshot 2022-02-09 at 11 14 29 PM" src="https://user-images.githubusercontent.com/48582859/153339693-1df59b32-842f-4151-9109-c0c030a83da7.png">

**Comment by chanakyaken** [comment]
> One suggestion after the plot is rendered is you can remove the loading message from the background.

Hi Saurabh,

Thanks for using our app and giving us the positive feedback.
The issue you mentioned is known to us but we were not able to implement it due to the time constraint, we will try to get it changed in the coming releases.

Thank you
