### ISSUE TITLE
Napkin Diagram

### ISSUE THREAD

**Issue by Abhinav805** [airavata-courses/epsilon#5]
Create a Napkin Diagram.
Should show how it works in a simpler manner
Easy to understand to anyone

**Comment by Abhinav805** [comment]
![Napkin](https://user-images.githubusercontent.com/84340281/152554536-644517eb-2a6a-46a8-a291-973201b3624b.jpg)

**Comment by Abhinav805** [comment]
The user wants to check the weather of a city at a particular date. So he logged into the website and then in search tab enter the city and date and click on the search. It returns the required output for the user.

**Comment by chanakyaken** [comment]
Fixed with commit 2cb05b4d0aacc40bec515e12a2d97d05275c62d4

**Comment by Abhinav805** [comment]
All ok now.
