### ISSUE TITLE
Architecture Diagram

### ISSUE THREAD

**Issue by Abhinav805** [airavata-courses/epsilon#6]
Create a Architecture for the project.
Should show proper flow of the project with technology used

**Comment by Abhinav805** [comment]
![image](https://user-images.githubusercontent.com/84340281/152556678-a2433b4d-c86b-4a20-9ace-6c9af41bfde1.png)

**Comment by chanakyaken** [comment]
Fixed with commit c74a6154f368f2d9655249aa5d80bdc2dcd29c81

**Comment by chanakyaken** [comment]
Fixed with commit c74a6154f368f2d9655249aa5d80bdc2dcd29c81

**Comment by chanakyaken** [comment]
![Architecture Diagram](https://user-images.githubusercontent.com/94653406/152887535-32052466-51cf-445d-a599-01a2b4644883.jpeg)

**Comment by chanakyaken** [comment]
All ok

**Comment by pbrm4** [comment]
https://miro.com/app/board/uXjVOU0VISQ=/?invite_link_id=499323733261
Refer this for Diagram link.
